server:
  port: 9005
spring:
  application:
    name: ES-SERVICE
  data:
    elasticsearch:
      cluster-name: my-ealsticsearch
      cluster-nodes: 127.0.0.1:9300
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
